// <auto-generated />
namespace Locadora.Filmes.Dados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MigracaoEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigracaoEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "202010230025463_MigracaoEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
