// <auto-generated />
namespace Locadora.Filmes.Dados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AdiicaoAutor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdiicaoAutor));
        
        string IMigrationMetadata.Id
        {
            get { return "202009180048411_AdiicaoAutor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
